2020-05-26 14:58:49,513 INFO: Wills Website [in /Users/wx/Documents/GitHub/Wills_Flask_Website/app/__init__.py:79]
2020-05-26 14:58:50,891 ERROR: Exception on /favicon.ico [GET] [in /Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/app/errors.py", line 11, in not_found_error
    return render_template('404.html'), 404
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/app/templates/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/wx/Documents/GitHub/Wills_Flask_Website/app/templates/404.html", line 5, in block "content"
    <p><a href="{{urlfor('index')}}">Back</a></p>
jinja2.exceptions.UndefinedError: 'urlfor' is undefined
2020-05-27 13:50:44,653 INFO: Wills Website [in /Users/wx/Documents/GitHub/Wills_Flask_Website/app/__init__.py:79]
2020-05-27 13:51:22,146 INFO: Wills Website [in /Users/wx/Documents/GitHub/Wills_Flask_Website/app/__init__.py:79]
2020-05-27 13:51:35,073 INFO: Wills Website [in /Users/wx/Documents/GitHub/Wills_Flask_Website/app/__init__.py:79]
2020-05-27 14:16:10,784 INFO: Wills Website [in /Users/wx/Documents/GitHub/Wills_Flask_Website/app/__init__.py:79]
2020-05-27 14:17:35,673 INFO: Wills Website [in /Users/wx/Documents/GitHub/Wills_Flask_Website/app/__init__.py:79]
2020-05-27 14:17:49,729 INFO: Wills Website [in /Users/wx/Documents/GitHub/Wills_Flask_Website/app/__init__.py:79]
2020-05-27 14:18:52,553 INFO: Wills Website [in /Users/wx/Documents/GitHub/Wills_Flask_Website/app/__init__.py:79]
